Masterminds/glide

cmd/get_imports.go, cmd/git.go
For simple dependency configurations like:
```
- package: github.com/spf13/viper
vcs: git
ref: 90734830d1ec30c19cb03e3ecd76a43dc1618b01
```
(package/vcs specified, but no repo) `glide update` did not work as expected. This patch brings the update feature up on par with `glide install` for these cases.
Please also see issue #40.
=> Fix 'glide update' for new dependencies, if no repo configured for git/hg.

cmd/git.go
This patch adds the much-needed functionality of checking the repository type and remote of the current checkout of a git dependency against the configuration.
If the remote `origin` does not match whatever is configured as repo, a fresh clone is initiated after wiping the dependencies source directory.
As discussed in #30, this allows switching to a fork, or different remote location for any git dependency, by merely changing `glide.yaml` (and running `glide update` for example as part of the CI process).
=> Add support for changed VCS type or repository for Git. Issue #30.

README.md, cmd/get_imports.go, cmd/recursive_glide.go, cmd/util.go, cmd/yaml.go, cmd/yaml_test.go, docs/example-glide.yaml, glide.go, glide.yaml
This is a prototype of #55 
It adds a `flatten` option that takes `true` or `false` as an option.
When set to `true`, any sub package vendored in with the same name will be skipped.
When set to `false`, business as usual.
A few other changes of note:
- []*Dependency was made into a type Dependencies so I could put common `Get` by name functionality on it. There may be code elsewhere that can use this.
* Added `boolOrDefault` to work with the yaml and having a default bool set
* Added the concept of a Config.Parent and some funs related to it traversing up the tree.
* Enhanced some of the yaml tests for new and existing functionality.
=> Add flatten open to imports

cmd/link_package.go, cmd/util.go
This patch keeps glide from breaking if GOPATH is not set.
**EDIT**: With the second commit I essentially made both functions `Gopath()` and `Gopaths()` behave in a more predictable way.
=> More robust GOPATH retrieval

glide.go
The README lists the command as `import godep`, but that was resulting
in:
Oops! Command glide-godep does not exist.
I think this is the right solution, but don't quite grok the cookoo
rabbit hole yet, so might be off base - there are a lot of godep/godeps
references around. This makes it work as promised at least :-).
=> Fix `import godep` subcommand reference

cmd/msg.go, cmd/util.go, glide.go
This is incredibly useful for certain environments which do not support ansi color codes. For example, in my use case, we were running glide install in jenkins, where the color codes do not work and just add junk to the output.
=> Add a --no-color flag to remove color codes from output

README.md
subpackages directive must be plural.
Contents of the subpackages directive must be a yaml list.
=> Fix example glide.yaml in README.

action/list.go, dependency/resolver.go, dependency/resolver_test.go, glide.go, repo/installer.go, repo/vcs.go
This walks the import tree rather than the file system to find the imports to download.
Nice work @technosophos 
I think there are two things still to do:
=> Resolve the imports being used

action/ensure.go
Fix the Ensure command to make sure that GO15VENDOREXPERIMENT is evaluated for Go 1.6.
=> Handle GO15VENDOREXPERIMENT flag for >=Go 1.6

util/util.go
Is this correct? e.g. `+` instead of `&` on the querystring?
Also I wonder where are the upstream specs for this feature
=> Use correct ampersand to append parameters to querystring

.travis.yml
This adds build support for both Go 1.6 and Go "tip"
If there is a way to make errors on tip non-fatal, we should do that.
=> Add support for Go 1.6 and Go Dev to Travis

repo/vcs.go
Part of the change for #264 
Addresses the skipping branch caching step if caching is disabled.  
Still needs fix for global cache disabled flag in `repo/cache.go`
=> Do not try to cache branch if caching is disabled

dependency/resolver.go, repo/installer.go, repo/vcs.go
This happens when the directory exists for a root repo location but
it contains no files. Glide thinks it exists but it's a broken
location.
The fix here detetects the problem and fetches a fresh copy of
the package.
=> Fixed #275, #285: Empty package location causes errors

repo/vcs.go
This is a big reduction in non-useful noise when running.
=> Make 'already set' be a debug message

dependency/resolver.go
`resolveImports` did not check for `.HasIgnore` when building the final package list to update/install.
=> Fixes 304: glide tries to update ignored packages

dependency/resolver.go
While understanding the output of the tool, I noticed this.
=> Don't call SetVersion() twice

cfg/config.go, glide.go, repo/installer.go, repo/tracker.go, repo/tracker_test.go, repo/vcs.go
This does a few things:
* Builds on #309 (which can now be closed).
* Handles map writing in a concurrency safe manner. As of Go 1.6 the runtime will panic if maps are concurrently written/read from.
* Moves the updated tracking from the config instance to the installer.
=> Track updated packages to avoid dup work

repo/vcs.go
The caller will log the same error
=> Don't double-print SetVersion() failure

gb/gb.go, godep/godep.go, gom/gom.go, gpm/gpm.go
This is imperfect - it says:
```
Found Godeps.json file in /home/thockin/tmp/glide/src/k8s.io/kubernetes/vendor/github.com/opencontainers/runc
```
when it would be better to say:
```
Found Godeps.json file in vendor/github.com/opencontainers/runc
```
or:
```
Found Godeps.json file in k8s.io/kubernetes/vendor/github.com/opencontainers/runc
```
or:
```
Found Godeps.json file in vendored github.com/opencontainers/runc
```
Better fixes would be welcome instead of this, but this is better than nothing.
=> Print the path a recursive deps file was found in

Makefile, action/get.go, action/install.go, action/update.go, glide.go, godep/godep.go, godep/strip/strip.go, godep/strip/strip_test.go, path/strip.go, path/strip_test.go
@technosophos @sgotti @thockin can you please take a look at this.
=> Add ability to remove nested vendor and Godeps/_workspace directories

dependency/resolver.go
The drive letter case would differ on Windows, causing
attempted vendoring of sub packages.
Fixes #290 : `glide update` vendors current repo if it contains subpackages
=> Use case insensitive path comparison on Windows

action/ensure.go, util/util.go
When the package in the glide.yaml does not match the current
location in the GOPATH warn the users.
=> Fixes #371: Warn when name/location mismatch

action/list.go, action/list_test.go, glide.go
Sort of addresses #256. Might be worth having a format which spits out a newline delimited list, without the "INSTALLED/MISSING/GOPATH packages" headers.
=> glide list: support json output format

glide.go
Previously it read...
```
DESCRIPTION:
This uses the native VCS of each package to try to
pull the most applicable updates. Packages with fixed refs (Versions or
tags) will not be updated. Packages with no ref or with a branch ref will
be updated as expected.
```
Now it's in the form:
```
DESCRIPTION:
This uses the native VCS of each package to try to
pull the most applicable updates. Packages with fixed refs (Versions or
tags) will not be updated. Packages with no ref or with a branch ref will
be updated as expected.
```
Indentations were using tabs and should have been 3 spaces.
=> Fixed help text display indentation

Makefile, action/ensure.go, action/rebuild.go, util/util.go
The Google App Engine SDK ships with a python wrapper called goapp instead of the regular go executable.
Usage example:
`GLIDE_GO_EXECUTABLE=goapp glide install`
Current workaround is to install both go and go-app-engine-64 packages.
=> Added support for custom Go executable name.

util/normalizename_test.go, util/util.go
When the name passed to util.NormalizeName contains backslashes from a
Windows filepath, the backslashes must be first converted to forward
slashes (used by all package names, including on Windows).  This fixes
the strings.TrimPrefix call used to strip the repo root from the
subpackage.
As a result of this, subpackages in lockfiles are written identically
on Windows as other Unix platforms and no duplicate subpackages are
introduced.
Fixes #389.
=> Correctly normalize Windows package paths.

glide.lock, glide.yaml, vendor/github.com/Masterminds/vcs/CHANGELOG.md, vendor/github.com/Masterminds/vcs/git.go, vendor/github.com/Masterminds/vcs/vcs_remote_lookup.go, vendor/github.com/Masterminds/vcs/vcs_remote_lookup_test.go
Note, codegangsta/cli is set to use releases (which were recently
pushed). This ended up causing no change to cli as Glide was
already using the same commit.
=> Updating to VCS 1.6.1

action/create.go
`guessDeps` is a rather long function (and there is a comment at the top acknowledging so). Let's try to extract to some of the functionality out of it to make it easier to read. This groups all of the Import related dependency guessing into a single function called `guestImportDeps` and moves that logic out of the `guessDeps` functions, making things more concise in `guessDeps`.
My long term plan is to keep refactoring this file until it's easier to test. This is a nice step in the direction of making this file more testable.
=> extract guessImportDeps function

msg/msg.go
The type [INFO], [DEBUG], etc are now a uniform width column no
matter the message. The messages themselves start at the same
indentation. This should improve readability.
=> Updating message indentation to be uniform

glide.go
Hi,
We are evaluating moving over to glide for the rkt project. While testing bits out I found that the `--delete` flag in the `glide update`/`glide install` subcommand actually didn't do anything.
=> Fix DeleteUnused flag

README.md
I am not entirely sure if this is the correct explanation in the context of this project but https://github.com/golang/go/wiki/PackageManagementTools suggests that `GO15VENDOREXPERIMENT` is for 1.5 Go release. 1.6 release makes the vendoring the default behavior.
=> export GO15VENDOREXPERIMENT only on 1.5

dependency/resolver.go
Imagine the following scenario: A user has a Go project. This directory is sitting in an arbitrary location in their file system and the user would like to keep it there. However, they need it to work with Go tooling, so they symlink it into an appropriate location in their GOPATH, e.g. `$GOPATH/src/github.com/user1/myproject`. The user then decides they's like to start using glide, so they cd to `$GOPATH/src/github.com/user1/myproject` and run `glide create` to generate their initial `glide.yaml` file. The result is the creation of empty `glide.yaml` file. Sad times.
What's happening is that the `basedir` given to `NewResolver` is actually a symlink. This in turn causes an issue in the `ResolveLocal` function. The `if !fi.IsDir()` check fails since the basedir isn't actually a directory, …
=> add ability to read symlink basedirs

docs/glide.yaml.md
Make the indentation level for both `owners` the same.
=> Fix indentation of example glide.yaml

action/config_wizard.go, action/create.go, action/get.go, action/get_test.go, action/install.go, action/list.go, action/remove.go, action/update.go, cfg/config.go, cfg/lock.go, dependency/resolver.go, dependency/resolver_test.go, dependency/scan.go, docs/glide.yaml.md, glide.go, glide.lock, repo/installer.go, repo/set_reference.go, repo/vcs.go, tree/tree.go
This is ready to be tested. `glide init` finds test dependencies. `glide update` resolves their tree, unless flag opts-out, and `glide install` will install them (unless opt-out flag is used).
Note, test dependencies in vendor/ are not handled. Just those in local codebase.
=> Resolve Test Imports

docs/versions.md
Per #483, "<= 2.x is equivalent to <= 3" should actually be "< 3" since
3.0 does not satisfy `<= 2.x`.
=> fix for #483

action/install.go, cfg/config.go, cfg/lock.go, repo/installer.go
Lightly refactor some lockfile logic into shared functions, so callers inside & outside glide do things the same way.
Personally I need this to create a glide plugin (as requested in PR #266), for which I need to read the lockfile, and turn those `Lock` structs into `Dependency` structs. These helper funcs will ensure that if anything changes in glide, my (and others') plugin will keep up.
(Also moving the `LoadLockfile` func has been a `TODO` in the code for a while)
=> Make shared funcs for lockfile usage

repo/installer.go, repo/vcs.go
For 'glide install', this lazily computes whether the existing vendor
checkouts are already at the right commit. If they are, those deps are
skipped during the concurrent update.
This is safe to do in install because the dependency graph is already
computed, so there should never be a case where the glide.lock file does
not contain a negotiable dependency graph.
=> Glide install skips fetch when it is up to date

action/get.go, action/install.go, action/update.go
Fixes #499 by logging any error that occurs when stripping version control data from dependencies.
=> Log an error if stripping version control data fails

godep/strip/strip.go
This fixes an issue where if a repository has a file named "vendor", glide would crash. This scenario could be encountered because a repo symlinks "vendor" to "Godeps/_workspace/src".
Possibly related: https://github.com/golang/go/issues/16280
=> Only skip directories when rewriting godeps

cfg/config.go, cfg/lock.go, cfg/lock_test.go
This alters the YAML marshaling to sort import and devimport subpackage
sections.
Closes #521
=> Sort subpackages for glide.yaml and glide.lock

util/normalizename_test.go, util/util.go
When import unknown host package with sub, glide show following error.
when,
```
import:
- package: otherurl/example/root
repo: git@otherurl:example/root.git
vcs: git
subpackages:
- sub
```
then,
```
[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Fetching updates for otherurl/example/root/sub.
[WARN]  otherurl/example/root/sub appears to be a vendored package. Unable to update. Consider the '--update-vendored' flag.
[ERROR] Failed to set version on otherurl/example/root/sub to : Cannot detect VCS
```
Because `getRootFromGoGet(pkg string) string` method get `https://otherurl/example/root/sub` and it failed.
But, fetching root is success and cached in `remotePackageCache`, so compare prefix to cached packages.
Does this resolve #469 ?
=> Fix NormalizeName for subpackage of unknown host

path/path.go, path/path_test.go, path/strip.go, path/strip_test.go, testdata/path/x/vendor
If `vendor` is a symlink to another directory (for example, `__vendor`), `filepath.Walk` will not descend into it, preventing `--strip-vcs` and `--strip-vendor` from working. Appending `os.PathSeperator` is enough to resolve the symlink.
I'm not sure if this is the ideal solution, but I copied the pattern from [`glide-vc`](https://github.com/sgotti/glide-vc/blob/master/gvc.go#L117) which works as expected on symlink'd vendor directories.
=> Resolve vendor directory symlinks

CHANGELOG.md, action/install.go, action/update.go, dependency/delete.go
Note, there was also a mishandling of testImport that was fixed
=> Fixed #529: --delete flag deletes and redownloads transitive deps

tree/tree.go
Checks for error while walking directories and propagates them up to prevent panic. Fixes issue #440.
=> Fixes panic while running tree command

CHANGELOG.md, action/get.go, action/update.go, cfg/lock.go, repo/installer.go, repo/set_reference.go
There were two reasons for this
1. The case there import was empty but testImport was not
2. When the same dependency appeared in both import and testImport
thre was a race condition that could cause failure
=> Fixed #517 failed to install testImport from lock

.travis.yml, Makefile
This is quick and dirty but will catch some errors not otherwise
caught.
=> Add an integration test setup on test runs.

dependency/resolver.go, dependency/resolver_test.go
When a file or directory message is present it usually means a
subpackage is not present due to a version conflict. Noting this
with directions.
=> Fixed #287: When file or directory not found provide useful message

Makefile
For this to work with `gox` this [gox PR](https://github.com/mitchellh/gox/pull/69) needs to be merged.
While it does not happen (And I don't know if someday it will), it's possible to use the fork https://github.com/franciscocpg/gox.
After merging this PR, it is necessary to run `make dist` and publish the new arm dists to the latest glide release.
Also this [glide.sh PR](https://github.com/Masterminds/glide.sh/pull/6) needs to be merged so one can install glide on a arm device with `curl https://glide.sh/get | sh`.
=> Build with arm versions

action/debug.go, glide.go, msg/msg.go
The verbose logging in the messenger isn't used anywhere, so this removes the command line
flag as well as cleaning up additional unused functions and fields. This is intended to address issue #568.
=> Remove verbose flag

repo/installer.go
This was happening when a sub-package imported before the top level
or if the top level for the project not imported at all.
=> Fixed #599: In some cases not importing dependencies config

dependency/resolver.go
The resolver loop caused Kubernetes imports to fail.
=> Fixed #615: There was a way Glide could get stuck in a resolver loop

CHANGELOG.md, repo/installer.go
=> Try to preserve vendor/.git, if it exists

docs/plugins.md
`glide-cleanup` is to check and remove unused packages from the `glide.yaml` file.
=> Add glide-cleanup plugin

glide.go
* Fix wording of description for install command
* Fix typo in deprecated warning for `--file` flag
=> Fix documentation issues in glide.go

repo/vcs.go
It seems that mostly sentences that indicate an action ("Xing something") do not end in a dot. But some did. So it's either all of them or none: I changed it to none, dots at the end of these messages look strange.
=> Make ending dots in prints more consistent

path/path.go
`path.Home()` does not return user's home directory even if it exists.
I think this is because incorrect `err` checking.
=> Fix glide home directory

docs/plugins.md
Adds a link to the glide-pin plugin for pinning all discovered dependencies in the `glide.lock` file explicitly in the `glide.yaml` file. Respects version ranges, but will replace them if the `--exact` flag is used.
=> Add glide-pin plugin

util/util.go
When GOROOT is not set as an environment variable, GetBuildContext
fetches it from 'go env GOROOT', which takes about 50ms on my machine.
This overhead can almost double the time it takes to run an update since
GetBuildContext is called relatively frequently.
Instead, read GOROOT during initialization and cache it for
GetBuildContext.
=> Cache GOROOT at init time

path/path.go
In Go 1.8 a default GOPATH was introduced. This can be retrieved
using `go env GOPATH`. This change updates Glide to check for a
default value when the GOPATH is not set. The reason to invode the
go toolchain as a second step is to avoid invoking it if possible.
=> Fixes #771: Handling default GOPATH for Go 1.8

Makefile
Hi,
I'm packaging this software for a source based distribution [(Exherbo)](https://exherbo.org/). During the compilation, we are not in a git repository (I use Github tarball). Because of that, the `$(shell git tag --describe`) will emit an error even if I pass the `VERSION` to `make` like: `make build VERSION=0.12.3`
The error is harmless and the build still succeed but it can make the user think that the compilation will fail :-)
=> Build: use VERSION if provided or fallback to git tag --describe

repo/installer.go
When vendor is a submodule, .git is a file (not a directory). When /tmp is on a
different filesystem, we try to copy it as a directory which leaves an empty
.git directory instead of the file. This change fixes this by copying it as a
file in this case.
Fixes #828.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/masterminds/glide/829)
=> Preserve .git file correctly

path/strip.go, path/winbug.go, repo/installer.go
For an example of the issue and status on Go itself see
https://github.com/golang/go/issues/20841
When working with large file sets such as those in a large dependency
tree (e.g. thousands of files) functions such as os.RemoveAll and
os.Rename can fail on Windows and Windows Subsystem for Linux. The
system commands work without issue.
This change detects Windows and the WSL environments then drops
down to system commands to make these changes. On mac, linux, and
other the os package functions are still used.
=> Fixed #778: Removing and moving large sets of files fails on Windows

dependency/resolver.go
In go 1.9 there was a change to the way ImportDir, or rather Import
with a local "." package, responded when not found. Previously,
the error was an OS not found error that could be detected by
os.IsNotExist. Now the error is a custom go error using the format:
fmt.Errorf("cannot find package %q in:\n\t%s", path, p.Dir)
This change looks for both cases. For Go 1.9 is checks of it doesn't
exist because there are similar errors in go/build.
For more detail on the Go side of this see https://github.com/golang/go/issues/21923
=> Fix issue due to go/build.ImportDir change response on not found dir

Makefile
Added support for  linux/s390x arch in glide. 
Please review.
=> Added support for s390x

dependency/resolver.go, tree/tree.go
This PR addresses glide's handling of go build tags for `math/bits` (added in go1.9). 
One example use I found [here](https://github.com/RoaringBitmap/roaring/blob/master/ctz.go#L1-L3)
Similar to: 
- https://github.com/Masterminds/glide/pull/376
- https://github.com/Masterminds/glide/issues/432
=> Fix math/bits go build tags

dependency/resolver.go
This should help with issue https://github.com/Masterminds/glide/issues/1055.
=> crypto ed25519 added to stdlib in go1.13

godep/strip/strip.go
Fixes #975
When deleting 'Godeps/_workspace' folders the `Walk` function may be called for already deleted entries (e.g.  Godeps/_workspace/.gitignore) afterwards.
To reproduce the segfault try this glide.yaml:
```
package: github.com/databus23/glide-sigfault
import:
- package: github.com/yudai/golcs
version: 3aebbac3964febd3fa3189f5d9db214cc6e940a6
```
```
$> glide install -v
[INFO]	Lock file (glide.lock) does not exist. Performing update.
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching updates for github.com/yudai/golcs
[INFO]	--> Setting version for github.com/yudai/golcs to 3aebbac3964febd3fa3189f5d9db214cc6e940a6.
[INFO]	Resolving imports
[INFO]	Downloading dependencies. Please wait...
[INFO]	Setting references for remaining imports
[INFO]	Exporting resolved …
```
=> Fix segfault with Glide 0.13.2 when stripping Godep workspace
