Masterminds/glide

cmd/git.go

Upon updating a Git dependency, check if the current checkout matches whatever _ref_ or _tag_ (intentionally skipping branches that might change on the remote side, tags SHOULD not) is configured.
This speeds up the `glide update` run tremendously for bigger projects.

Skip "git fetch" if current checkout matches configured ref or tag.

---

cmd/guess_deps.go
cmd/tree.go
cmd/util.go

Fixes incorrect build context when $GOROOT env var not set

---

README.md

This pull request updates the README.md file with complete build instructions.

Update README with build instructions, fixes #132

---

action/ensure.go

Fix EnsureGopath when multiple Gopaths

---

action/ensure.go

The new version scanning treates <1.5 as unsupported, =1.5 as
supported only if GO15VENDOREXPERIMENT=1, and > 1.5 as supported
UNLESS GO15VENDOREXPERIMENT=0.
Currently, we detect 1.5 by go version. That will not work for some
dev checkout/build of 1.5.
Fixes #279

Add version scanning for >=1.7.

---

action/get.go

This short-circuits a 'get' if there was nothing to actually get.

Don't process deps if 'get' was a no-op

---

README.md
action/import_gom.go
glide.go
gom/gom.go
gom/parser.go
importer/importer.go

This PR adds support for importing [gom](https://github.com/mattn/gom)'s Gomfile.

Add support for importing Gomfile's

---

repo/vcs.go

Just fix typo for "uncommitted".

Fix typo "uncommitted"

---

.travis.yml
README.md

Migrating chat to Gitter

---

dependency/resolver.go

Allow relative imports using ../ to be ignored

---

glide.lock
glide.yaml
vendor/github.com/Masterminds/vcs/CHANGELOG.md
vendor/github.com/Masterminds/vcs/bzr.go
vendor/github.com/Masterminds/vcs/bzr_test.go
vendor/github.com/Masterminds/vcs/errors.go
vendor/github.com/Masterminds/vcs/errors_test.go
vendor/github.com/Masterminds/vcs/git.go
vendor/github.com/Masterminds/vcs/git_test.go
vendor/github.com/Masterminds/vcs/hg.go
vendor/github.com/Masterminds/vcs/hg_test.go
vendor/github.com/Masterminds/vcs/repo.go
vendor/github.com/Masterminds/vcs/svn.go
vendor/github.com/Masterminds/vcs/svn_test.go
vendor/github.com/codegangsta/cli/README.md
vendor/github.com/codegangsta/cli/app.go
vendor/github.com/codegangsta/cli/app_test.go
vendor/github.com/codegangsta/cli/category.go
vendor/github.com/codegangsta/cli/command.go
vendor/github.com/codegangsta/cli/help.go

- github.com/Masterminds/vcs to version 1.6.0
- github.com/codegangsta/cli to the latest tip of head. This
included a new subcommand category feature

Updated dependencies:

---

repo/cache.go

The latest version of Go (tip) is causing errors with the cache key generation now. For example, see https://travis-ci.org/Masterminds/glide/jobs/125481538

Creating the cache key did not handle SCP properly

---

README.md

Hello,
I am proposing this pull request to announce that I am publishing *glide* through PPA (https://launchpad.net/~masterminds/+archive/ubuntu/glide).
I created a team called masterminds (https://launchpad.net/~masterminds) at launchpad and I'd like to add @mattfarina as an admin member of this team (If he wants to, of course).
The project that automates this publishing is here (https://github.com/franciscocpg/glide-ppa) but is still *beta*. Once this project becomes stable I'd like to transfer its ownership to *Masterminds* (again, if there is some interest in doing so).
My next goal is publishing to [snappy](https://developer.ubuntu.com/en/snappy/) as this is going to replace deb packages in the future.

 Instructions to install from PPA

---

README.md

Hi  guys.
Because of this [issue](https://github.com/Masterminds/glide/issues/403) I am publishing glide to Xenial ubuntu with PPA.
Also can you please approve this [PR](https://github.com/Masterminds/glide-ppa/pull/1)?

Xenial PPA dist

---

action/ensure.go

Changed 'Wihtout' to 'Without'.

Fixed typo in action/ensure.go

---

action/config_wizard.go

Edit 'major.minor.path' to be 'major.minor.patch'.

Fix typo in config wizard

---

msg/msg.go

Enables logging of VCS error output when `--debug` is enabled.
I don't know if this is the ideal design — to be sure, the VCS error isn't ideal, and there's no central error reporting mechanism other than `msg`, which is why I extract the error there.
If I were to improve this, it'd be to encapsulate "some program failed to run and this is its failure info" as an error interface.
But I was fed up with getting unhelpful error messages ("Unable to get repository") from Glide, and this fixes that.

Log VCS error output as debug messages

---

dependency/resolver.go

Include XTestImports in resolver

---

repo/installer.go

Summary
---
* Fixes #558 
* Example: https://travis-ci.org/ory-am/dockertest/jobs/153426938

Fix:558 Fix panic() from nil error

---

CHANGELOG.md

Just a simple copy paste issue :)

Fix bad release number in the CHANGELOG.md

---

docs/commands.md
docs/getting-started.md
docs/plugins.md
docs/resolving-imports.md

Fix doc typos

---

path/path_test.go
path/winbug.go

* Fixed whitspace issues where spaces were used
* Fixed place there Fatal was used instead of Fatalf
* Updated constant to use the proper formatting

Lint and vet cleanup
